{
 "title": "Supavisor Pooler",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "tenant", "label": "Project", "query": "oaguxblfdassqxvvwtfe" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Supavisor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Downstream network usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(region) (increase(supavisor_client_network_send{tenant=~\"$tenant\"}[$__rate_interval]))",
     "legendFormat": "send {{region}}"
    },
    {
     "expr": "sum by(region) (increase(supavisor_client_network_recv{tenant=~\"$tenant\"}[$__rate_interval]))",
     "legendFormat": "recv {{region}}"
    }
   ]
  },
  {
   "title": "Upstream network usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(region) (increase(supavisor_db_network_send{tenant=~\"$tenant\"}[$__rate_interval]))",
     "legendFormat": "send {{region}}"
    },
    {
     "expr": "sum by(region) (increase(supavisor_db_network_recv{tenant=~\"$tenant\"}[$__rate_interval]))",
     "legendFormat": "recv {{region}}"
    }
   ]
  },
  {
   "title": "The total count of active clients",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by(region, mode) (supavisor_connections_active{tenant=~\"$tenant\"})",
     "legendFormat": "{{region}} - {{mode}}"
    }
   ]
  },
  {
   "title": "Pool checkout duration - local",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by(le) (increase(supavisor_pool_checkout_duration_local_bucket{tenant=~\"$tenant\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Client query duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by(le) (increase(supavisor_client_query_duration_bucket{tenant=~\"$tenant\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Pool checkout duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(supavisor_pool_checkout_duration_local_bucket{tenant=~\"$tenant\"}[$__rate_interval])))",
     "legendFormat": "local - p99"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(supavisor_pool_checkout_duration_local_bucket{tenant=~\"$tenant\"}[$__rate_interval])))",
     "legendFormat": "local - p90"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(supavisor_pool_checkout_duration_local_bucket{tenant=~\"$tenant\"}[$__rate_interval])))",
     "legendFormat": "local - p50"
    },
    {
     "expr": "histogram_quantile(0.1, sum by(le) (rate(supavisor_pool_checkout_duration_local_bucket{tenant=~\"$tenant\"}[$__rate_interval])))",
     "legendFormat": "local - p10"
    },
    {
     "expr": "histogram_quantile(0.1, sum by(le) (rate(supavisor_pool_checkout_duration_remote_bucket{tenant=~\"$tenant\"}[$__rate_interval])))",
     "legendFormat": "remote - p10"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(supavisor_pool_checkout_duration_remote_bucket{tenant=~\"$tenant\"}[$__rate_interval])))",
     "legendFormat": "remote - p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(supavisor_pool_checkout_duration_remote_bucket{tenant=~\"$tenant\"}[$__rate_interval])))",
     "legendFormat": "remote - p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(supavisor_pool_checkout_duration_remote_bucket{tenant=~\"$tenant\"}[$__rate_interval])))",
     "legendFormat": "remote - p99"
    }
   ]
  },
  {
   "title": "Pool checkout duration - remote",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum by(le) (increase(supavisor_pool_checkout_duration_remote_bucket{tenant=~\"$tenant\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Queries count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "sum by(region) (increase(supavisor_client_queries_count{region=~\"$region\", host=~\"$nodehost\", tenant=~\"$tenant\"}[$__rate_interval]))",
     "legendFormat": "{{$region}}"
    }
   ]
  },
  {
   "title": "Client connection duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum by(le) (increase(supavisor_client_connection_duration_bucket{tenant=~\"$tenant\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Client query duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(supavisor_client_query_duration_bucket{tenant=~\"$tenant\"}[$__rate_interval])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(supavisor_client_query_duration_bucket{tenant=~\"$tenant\"}[$__rate_interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(supavisor_client_query_duration_bucket{tenant=~\"$tenant\"}[$__rate_interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.1, sum by(le) (rate(supavisor_client_query_duration_bucket{tenant=~\"$tenant\"}[$__rate_interval])))",
     "legendFormat": "p10"
    }
   ]
  },
  {
   "title": "Queries per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "sum by(region) (rate(supavisor_client_queries_count{tenant=~\"$tenant\"}[$__rate_interval]))",
     "legendFormat": "{{$region}}"
    }
   ]
  },
  {
   "title": "Attempted DbHandlers per second",
   "type": "timeseries",
   "description": "The total number of database connections by db_handler",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "sum by(region) (rate(supavisor_db_handler_db_connection_count{tenant=~\"$tenant\"}[$__rate_interval]))",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "Successful joins per second",
   "type": "timeseries",
   "description": "The total number of successful joins",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "sum by(region) (rate(supavisor_client_joins_ok{tenant=~\"$tenant\"}[5m]))",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "Failed joins per second",
   "type": "timeseries",
   "description": "The total number of failed joins",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "expr": "sum by(region) (rate(supavisor_client_joins_fail{tenant=~\"$tenant\"}[5m]))",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "Created DbHandlers per second",
   "type": "timeseries",
   "description": "The total number of created db_handler",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "sum by(region) (rate(supavisor_db_handler_started_count{tenant=~\"$tenant\"}[$__rate_interval]))",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "Stopped DbHandlers per second",
   "type": "timeseries",
   "description": "The total number of stopped db_handler",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "targets": [
    {
     "expr": "sum(rate(supavisor_db_handler_stopped_count{tenant=~\"$tenant\"}[$__rate_interval])) by (region)",
     "legendFormat": "{{region}}"
    }
   ]
  }
 ]
}